Add paymentData to OrderFormFragment
vtex-apps/checkout-resources pull request #33
Opened 2020-03-10 21:32 UTC by pedromtec

#### What problem is this solving?

Add `paymentData` to `OrderFormFragment`

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [ ] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Screenshots or example usage

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements 

#### Notes

2020-03-10 21:50 UTC, marcoskwkm requested changes
Do not erase the `How should this be manually tested?` part of the PR template, unless it is a _really_ trivial change. What we usually do in this case is add a link to a workspace using this app so we can be sure the query works.

2020-03-11 13:20 UTC, lucasecdb commented
also, please fill out the rest of the PR template, so we can distinguish better the types of change and motivation for this, and remove the optional unused sections such as notes and screenshot

2020-03-11 16:41 UTC, lucasecdb approved these changes

2020-03-11 16:44 UTC, darlenedms commented
@pedromtec check the mask the should be applied on input `onBlur` and navigation through `tab` (probably an issue of Styleguide component).

2020-03-11 17:10 UTC, darlenedms approved these changes

2020-03-11 17:11 UTC, marcoskwkm approved these changes

2020-03-11 17:11 UTC, merged