Add availableAccounts to OrderFormFragment
vtex-apps/checkout-resources pull request #46
Opened 2020-04-24 18:13 UTC by pedromtec

#### What problem is this solving?

`PaymentStep` needs to show the saved payment options. 

#### How should this be manually tested?

You need to have a saved card to see it.

[Workspace](https://paymentio--checkoutio.myvtex.com/)

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [x] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Screenshots or example usage
<img width="1439" alt="Screen Shot 2020-04-22 at 4 59 30 PM" src="https://user-images.githubusercontent.com/32311264/80143987-1c962280-8584-11ea-961e-ed3eeb8e4b7a.png">

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
✔️| New feature 
_ | Breaking change 
_ | Technical improvements

2020-04-24 18:40 UTC, lucasecdb approved these changes

2020-04-24 19:29 UTC, kevinch submitted a review, later dismissed

2020-04-24 19:31 UTC, lucasecdb requested changes
We need to fix the issue in `checkout-graphql` before merging this

2020-04-28 18:05 UTC, lucasecdb approved these changes

2020-05-05 14:11 UTC, kevinch approved these changes

2020-05-05 14:13 UTC, merged