CHK-440: Feat/pickup
vtex-apps/checkout-resources pull request #61
Opened 2020-11-19 13:55 UTC by jeffersontuc

#### What problem is this solving?

The same as https://github.com/vtex-apps/checkout-shipping/pull/18

#### How should this be manually tested?

N/A

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [x] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
✔️ | New feature 
_ | Breaking change 
_ | Technical improvements

2020-11-26 14:15 UTC, lucasecdb submitted a review, later dismissed

2020-11-26 17:51 UTC, wdsrocha submitted a review, later dismissed

2020-12-01 14:08 UTC, jeffersontuc commented
Rebased!

2020-12-01 14:14 UTC, lucasecdb requested changes

2020-12-01 14:14 UTC, lucasecdb commented on react/Mutations.tsx
> +  selectPickupOption,
we shouldn't update this file anymore

2020-12-01 14:15 UTC, jeffersontuc commented on react/Mutations.tsx
> +  selectPickupOption,
oh, it's true!

2020-12-01 19:47 UTC, jeffersontuc commented on react/Mutations.tsx
> +  selectPickupOption,
done.

2020-12-01 20:30 UTC, lucasecdb approved these changes

2020-12-01 20:56 UTC, wdsrocha approved these changes

2020-12-01 20:57 UTC, merged