ModalType prop added
vtex-apps/checkout-resources pull request #93
Opened 2022-03-17 10:21 UTC by HugoLaguna

#### What problem is this solving?

The fragments of  orderForm/item hasn't modalType prop, we create a PR to have it in [checkout-graphql](https://github.com/vtex-apps/checkout-graphql/pull/175).

2022-03-17 10:21 UTC, HugoLaguna commented
Patch (backwards-compatible bug fixes)

2022-03-17 10:22 UTC, HugoLaguna commented
There's nothing new to document

2022-03-22 13:03 UTC, jeffersontuc submitted a review, later dismissed

2022-03-22 13:57 UTC, lucasecdb approved these changes

2022-03-22 13:58 UTC, lucasecdb requested changes

2022-03-22 13:58 UTC, lucasecdb commented on CHANGELOG.md
> +## [Unreleased]+
```suggestion
## [Unreleased]
```

2022-04-13 09:36 UTC, HugoLaguna commented on CHANGELOG.md
> +## [Unreleased]+
fixed!

2022-04-18 19:04 UTC, jeffersontuc approved these changes

2022-04-18 19:09 UTC, lucasecdb approved these changes

2022-04-18 19:10 UTC, merged